version: '3'

services:
  db:
    image: mysql:5.7
    container_name: db-wordpress
    volumes:
      - ./data:/var/lib/mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: wordpress-gatsby
      MYSQL_DATABASE: wordpress
      MYSQL_USER: wordpress
      MYSQL_PASSWORD: wordpress-gatsby
  wordpress:
    image: wordpress:latest
    container_name: wordpress
    depends_on:
      - db
    volumes:
    - ./html:/var/www/html/
    ports:
      - "3000:80"
    restart: always
    environment:
      WORDPRESS_DB_HOST: db:3306
      WORDPRESS_DB_USER: wordpress
      WORDPRESS_DB_PASSWORD: wordpress-gatsby
  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    container_name: phpmyadmin-backend
    links:
      - db
    ports:
      - "5000:80"
    environment:
      PMA_ARBITRARY: 1
